# a=True
# b=False
# c=False
# d=True
# print(a==b)
# print(a!=b)
# print(b!=c)
# print(a!=d)
# print(b>c)
# print(c<d)
# print(a>=d)
# print(c<=b)
# print(a==d)
# print(b==c)
# print()
# print(a and b)
# print(a or b)
# print(not(a and c ))
# print(not(b or d))
# print(a and (b or c))
# print((a or b) and( c or d))
# print(not(a and d))
# print((b and c) or (a and d))
# print(a or(b and d))
# print(a and b) or (c and d)
# print()
# print((a and b) or (not(c or d) and ( a==b)))
# print((a==b or c<d)and (a!=d or b<c))
# print((a or b) and (c==d) or (not(a==c)))
# print(a and (b or c)) and not (d and(a==b))
# print(a and (b or c)) and not (d or(b and c))
# print(a or( b and c)) or (d==True) and (a or b) 
# print(a==d or(b and c)and not (a!=b))or(c<=d)
# print((a and b )or (c>d)) and not(a==c)and(b!=c)
# print((a and b)or (c==d)) and not (a!=d) and(c<b)
# print(a or(b and not c)or(d==True))and not (a==b and c!=d)
# print (not(a and b)or (c<d) and (b==False or d==True))
# print(not(a or b) and(c<=d or not (a==b)) and (c==b))
# print(a and(b or c)) or not (a==b) and (c!=d)
# print(a==True and b==False) or not (c==d)and(a or d)
# print((a==b) or not (c<=d)) and((b or c) and (a!=d))
# print(a or(b and (c<=d))) or not(a==c and d!=True)
# print(not( a and (b or(c and d))) or not (a==c and d!=True))
# print(not(a and(b or(c and d))) or (c==b and(a==d)))
# print(a and (b==False or c==True))and not (d and b)
# print(a or (b and(c or d))) and not (a==c or b!=d)
# print((a and b)or (c and d)) and not (a==c or b!=d)
# print(not (a and b)or not(c!=d)or (a==d and not(c!=b)))
# print(( a or b) and (c==True)) or (a==d and not (c!=b))
# print((a and b) or not (c==True)) and (a==b or(c<d))
# print(a or (b and not (c==d)) and (a!=d or( not (b==False))))
# print((a==d and not(b and c)) or (a!=c and b==True))and(c!=d)
# print((a or(b and c)) and d==True) or not(a==c)
# print(a and not (b or c)and (d==True)) or not(a and b)
# print((a and b)or ((c==True) and(d!=False))) and not (a==b)
# print(a==b and not(c and d)) or (a!=d and c==b)
# print((a==b and c!=d) or not(a and c)) and (a or(b and d))






